### ISSUE TITLE
I'm getting this error, the bot isn't going online on steam.

### ISSUE THREAD

**Issue by NotSoSuper** [Starfox64/FoxedBot#1]
root@NotSoSuper:/home/foxedbot.js# node app.js
Loading FoxedBot...
/home/foxedbot.js/node_modules/steam/lib/steam_client.js:18
th.join(__dirname, '../resources/protobufs/dota/steammessages.proto')).build()
                                                                      ^
TypeError: Cannot read property 'build' of null
    at Object.<anonymous> (/home/foxedbot.js/node_modules/steam/lib/steam_client.js:18:108)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/foxedbot.js/app.js:5:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by Starfox64** [comment]
Can you verify that **node_modules/steam/resources/protobufs/dota/steammessages.proto** is present?

**Comment by NotSoSuper** [comment]
nope, it's not. I installed it from the git repo, and when I try npm install steam it errors out.

**Comment by Starfox64** [comment]
Do you have svn installed?

**Comment by NotSoSuper** [comment]
yes. SUbversion?

**Comment by Starfox64** [comment]
Yes, do you have access to the svn command?

**Comment by NotSoSuper** [comment]
mhm

**Comment by NotSoSuper** [comment]
If you want, just add me on steam and I'll give you login :/
I'm gonna uninstall steam (npm) and try again.

**Comment by Starfox64** [comment]
Are you manually installing node-steam?

**Comment by NotSoSuper** [comment]
Yeah, I'm gonna try from npm install steam
and I'll post the results.

**Comment by NotSoSuper** [comment]
root@NotSoSuper:/home/node-steam-master# npm install steam
npm WARN install Refusing to install steam as a dependency of itself

**Comment by Starfox64** [comment]
Don't do it like that, download the latest version, I've completely restructured the Node.js app and added a package.json

https://github.com/Starfox64/FoxedBot#foxedbot-installation

**Comment by NotSoSuper** [comment]
It doesn't work when I do npm install steam

**Comment by Starfox64** [comment]
Don't do that, follow the instructions.
https://github.com/Starfox64/FoxedBot#foxedbot-installation

**Comment by NotSoSuper** [comment]
Oh, I thought it required me to install it >.>

**Comment by Starfox64** [comment]
No like I said I've completely changed the SteamBot.

**Comment by NotSoSuper** [comment]
I did everything there, the error in the first post is what happens when I try to launch it. I've configed it all.

**Comment by NotSoSuper** [comment]
https://gist.github.com/f50f438953f3b701be21

**Comment by NotSoSuper** [comment]
thats my config for the bot

**Comment by Starfox64** [comment]
What does it sayd when you run

```
npm install
```

In the install folder?

Where there is app.js and package.json

**Comment by NotSoSuper** [comment]
npm WARN package.json foxedbot@1.0.0 No repository field.
npm WARN package.json foxedbot@1.0.0 No README data
npm WARN cannot run in wd foxedbot@1.0.0 cd ./node_modules/steam && npm install (wd=/home/foxedbot.js)

**Comment by Starfox64** [comment]
It seems that npm cannot run properly where you installed the bot.

**Comment by NotSoSuper** [comment]
Ok, I'll put it somewhere else ;)

**Comment by Starfox64** [comment]
Actually is a permission issue, are you using a sudo user?

**Comment by NotSoSuper** [comment]
Just did, even tried sudo. Won't work.

**Comment by NotSoSuper** [comment]
Yeah, root.

**Comment by NotSoSuper** [comment]
I'm using ubuntu, should I try a different OS?

**Comment by Starfox64** [comment]
Run it with this argument

```
npm install --unsafe-perm
```

**Comment by NotSoSuper** [comment]
Worked :+1:

**Comment by NotSoSuper** [comment]
Thanks for the help, you're amazing.

**Comment by NotSoSuper** [comment]
Also, you should add steam guard support.
