### ISSUE TITLE
Error occuring when trying to use announce

### ISSUE THREAD

**Issue by Dunkstormen** [Starfox64/FoxedBot#13]
I have set up the bot and it works, unless when the bot is meant to send a message to the server.
Exactly which ports do i need to open in the firewall to make it work?

It just says An error occured while trying to connect to server <numer>.

**Comment by Starfox64** [comment]
_From README.md_
**Tip:** The ServerPort variable isn't the source engine port (27015), it is a specific port that will receive messages from the SteamBot.
2510X where X is the ServerID is a good way to avoid having the same port on two different servers.

On the machine where the bot is hosted you open the bot port and on the machine the garrysmod server is hosted you open the ServerPort (2510X)

**Comment by Dunkstormen** [comment]
My setings.js looks like this

![d1f1f8d506154f69524e68329c5272b3](https://cloud.githubusercontent.com/assets/7177605/6353884/32e64f3a-bc4c-11e4-8204-d99cb0c8fce4.png)

And the sv_config.lua on server 0

![1cbd1253260147e0dc25d3a4bcb0226b](https://cloud.githubusercontent.com/assets/7177605/6353953/a4765ed8-bc4c-11e4-865f-cda39f6f09ba.png)

**Comment by Starfox64** [comment]
First of all I hope for you the ServerKey and the bot password aren't the real ones because if they are you'd better be changing all of them now before someone steals your account.

Are the servers and bots on the same machine?

**Comment by Dunkstormen** [comment]
Yes they are on the same Machine :)

And just relax its just placeholder passwords :)

**Comment by Starfox64** [comment]
Then on the bot fir the servers IPs just use the loopback address (127.0.0.1) and for the SteamGuard code if you aren't using any don't put quotes on null.

Yon also don't need to open ports on your firewall.

**Comment by Dunkstormen** [comment]
Thank you alot for your help :+1:
I really appreciate that you're fast at answering when needed.
