### ISSUE TITLE
Bromsock module won't load

### ISSUE THREAD

**Issue by ghost** [Starfox64/FoxedBot#15]
I went through the install guide and have successfully connected the foxedbot js module to steam and can send messages to my foxedbot steam account without issues. Ping works and commands appear in the foxedbot command console.

The problem I am running into is that I can't get the foxedbot addon to initialize on my Garry's mod server (Windows). Here is the error text in my console log:

```
[FoxedBot] Initializing...

[ERROR] addons/foxedbot/lua/foxedbot/sv_foxedbot.lua:1: Couldn't load module library!
  1. require - [C]:-1
   2. unknown - addons/foxedbot/lua/foxedbot/sv_foxedbot.lua:1
    3. include - [C]:-1
     4. unknown - addons/foxedbot/lua/autorun/sh_init.lua:13


[ERROR] addons/foxedbot/lua/foxedbot/sv_callbacks.lua:4: attempt to call field 'addCallback' (a nil value)
  1. unknown - addons/foxedbot/lua/foxedbot/sv_callbacks.lua:4
   2. include - [C]:-1
    3. unknown - addons/foxedbot/lua/autorun/sh_init.lua:14

[FoxedBot] Initialized!
```

This tells me that the Bromsock module isn't loading. I made sure I downloaded the latest version and placed it in garrysmod\lua\bin and rebooted the server. This error appears every time the server tries to load. Either this is a bug or there is something more that needs to be done, but am unsure what.

**Comment by Starfox64** [comment]
After I did some looking around, it could be that the server doesn't have the C++ Runtime 32bit installed.

~~Install this: http://www.microsoft.com/en-au/download/details.aspx?id=30679 (x86)~~

**Comment by ghost** [comment]
I installed the 32 bit version first, started the GMod server software, and received the same error message on startup. I also went ahead and installed the 64 bit version, since I am running Win Server 2012 x64, and received the same error message.

One thing I did not do was reboot the entire machine after installing the update. I will try that later when there are fewer users on the system. Aside from the reboot, do you have any other ideas?

**Comment by Starfox64** [comment]
I just got told by the creator of bromsock to use this one.

http://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by ghost** [comment]
This solved the problem! Thanks for finding out. I recommend including this in the requirements to reduce confusion for future users.
