### ISSUE TITLE
players and listen commands no longer working

### ISSUE THREAD

**Issue by Zaddion** [Starfox64/FoxedBot#22]
Most of the commands work, but I cannot get "players" or "listen" to work anymore. I have selected the server and they are configured properly.

**Comment by Starfox64** [comment]
Can you describe what's not working.

**Comment by Zaddion** [comment]
It does not return anything, it'll say "You are now listening to all selected servers." but won't return any messages. Same with "players", it doesn't return anything.

**Comment by Starfox64** [comment]
I’m currently not at home and don’t have Garry’s Mod installed, I’ll check this issue this weekend.
