### ISSUE TITLE
Addon Error

### ISSUE THREAD

**Issue by theantihero** [Starfox64/FoxedBot#25]
The FoxedBot js works fine, but the addon has been giving me problems.

[ERROR] addons/foxedbot/lua/foxedbot/sv_events.lua:40: attempt to call field 'sendEvent' (a nil value)
1. v - addons/foxedbot/lua/foxedbot/sv_events.lua:40
   1. Run - gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:138
   2. func - addons/atlaschat/lua/atlaschat/init.lua:647
      1. unknown - lua/includes/extensions/net.lua:32

Doesn't see the server online as well. Tried running foxedbot_reload, but command doesn't even exist.

Also BromSock loaded fine, so that's not the problem.

**Comment by Starfox64** [comment]
Look for other error occurring earlier in the initialisation process.

**Comment by theantihero** [comment]
There is no other error during initialization :/

> [FoxedBot] Initializing...
> [FoxedBot] Initialized!
> [FoxedBot] Connected to FoxedBot.

**Comment by theantihero** [comment]
Oh wow... It's working O.o.. I got it to work by changing the bromsock dll name from gmsv_bromsock_linux_ubuntu.dll to gmsv_bromsock_linux.dll

works now.
