### ISSUE TITLE
Failure

### ISSUE THREAD

**Issue by SaengerItsWar** [Starfox64/FoxedBot#29]
Hello I have the FoxedBot installed like the Installation Guide and i got this failure

`root@purple-horizon-clan:/home/foxedbot.js# node app.js
Loading FoxedBot...
Unexpected string
`
The config

`module.exports = {
        /* The name of the SteamBot */
        botName: "Wave-Gaming.net Garry's Mod",
        
        /* The Steam username and password of the SteamBot */
        accountName: "saengerkrieglp",
        password: "*******",

        /* Enter location for ShaSentryFile */
        sentryfile: "./config/shasentry.bin",

        /* The ServerKey of the SteamBot */
        serverKey: "60554099411ABD13F722B781A2AC2655",

        /* The port that the SteamBot will listen on */
        botPort: 25000,

        /* The level of logging (TRACE/DEBUG/INFO/WARN/ERROR/FATAL) */
        logLevel: "INFO",

        /* Log ALL chat message (Not recommended unless debugging) */
        logChat: false,

        /* Sends messages even if the target is offline */
        sendOffline: false,

        /* Which SteamID64 are superadmins */
        admins: [
                "76561198125215911"
        ],

        /* Your Garry's Mod servers */
        servers: {
                "1": "[EU]wAVE Deathrun|Store|FastDL|",
                "2": "[EU]wAVE Bhop|Store|FastDL",
        }
};
`

**Comment by Starfox64** [comment]
Are you running the latest version of Node.js?

**Comment by SaengerItsWar** [comment]
I'm running Node.js 4.1.1

**Comment by Starfox64** [comment]
Could you try with Node.js 6.X.X?

**Comment by SaengerItsWar** [comment]
Ok now I'm using Node.js 6.10.2 and its the same error

**Comment by SaengerItsWar** [comment]
ok now i have fixed the failure but i have a another failure 
`root@purple-horizon-clan:/home/foxedbot.js# node app.js
Loading FoxedBot...
ProtoBuf.newBuilder is not a function`

**Comment by Starfox64** [comment]
Try running `npm install` again, if it still doesn't work use this `npm install protobufjs@5.0.1`.
Could you tell me what you did to fix it?

**Comment by SaengerItsWar** [comment]
I fixed it because I had two lines with // in the middle of the config (I had forgot to remove this lines from the standard config file) and now the bot is Running thx for your help

**Comment by SaengerItsWar** [comment]
and one question the gameserver are on a diferrent how that works?

**Comment by Starfox64** [comment]
In the addon's config you should set the other server's IP, you should also open the port in the firewall.

**Comment by SaengerItsWar** [comment]
and the addon makes Errors in my Console on the Garry's mod server.


`[ERROR] addons/foxedbot/lua/foxedbot/sv_events.lua:23: attempt to call field 'sendEvent' (a nil value)
1. fn - addons/foxedbot/lua/foxedbot/sv_events.lua:23
2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109`

**Comment by Starfox64** [comment]
Look further up the logs, there must be another error.

**Comment by SaengerItsWar** [comment]
ah i found it

L 04/27/2017 - 19:17:13: Lua Error: Couldn't include file 'includes/modules/bromsock.lua' (File not found) (@addons/foxedbot/lua/foxedbot/sv_foxedbot.lua (line 1))

L 04/27/2017 - 19:17:13: Lua Error: 
[ERROR] addons/foxedbot/lua/foxedbot/sv_foxedbot.lua:1: Module not found!
  1. require - [C]:-1
   2. unknown - addons/foxedbot/lua/foxedbot/sv_foxedbot.lua:1
    3. include - [C]:-1
     4. unknown - addons/foxedbot/lua/autorun/sh_init.lua:15


L 04/27/2017 - 19:17:13: Lua Error: 
[ERROR] addons/foxedbot/lua/foxedbot/sv_callbacks.lua:4: attempt to call field 'addCallback' (a nil value)
  1. unknown - addons/foxedbot/lua/foxedbot/sv_callbacks.lua:4
   2. include - [C]:-1
    3. unknown - addons/foxedbot/lua/autorun/sh_init.lua:16

**Comment by Starfox64** [comment]
You have not installed bromsock properly, if you can't figure it out ask on the bromsock thread.

**Comment by SaengerItsWar** [comment]
I have installed the bromsock.dll

**Comment by SaengerItsWar** [comment]
ok now i have this error:

[FoxedBot] Initializing...

[ERROR] addons/foxedbot/lua/foxedbot/sv_foxedbot.lua:1: Couldn't load module library!
1. require - [C]:-1
2. unknown - addons/foxedbot/lua/foxedbot/sv_foxedbot.lua:1
3. include - [C]:-1
4. unknown - addons/foxedbot/lua/autorun/sh_init.lua:15


[ERROR] addons/foxedbot/lua/foxedbot/sv_callbacks.lua:4: attempt to call field 'addCallback' (a nil value)
1. unknown - addons/foxedbot/lua/foxedbot/sv_callbacks.lua:4
2. include - [C]:-1
3. unknown - addons/foxedbot/lua/autorun/sh_init.lua:16

[FoxedBot] Initialized!

**Comment by CattoGamer** [comment]
If you are running on a Linux server then rename the file to
> gmsv_bromsock_linux.dll

otherwise on Windows 
> gmsv_bromsock_win32.dll

The solution for this error is.
> root@purple-horizon-clan:/home/foxedbot.js# node app.js Loading FoxedBot... Unexpected string

>     /* Your Garry's Mod servers */
>     servers: {
>             "1": "[EU]wAVE Deathrun|Store|FastDL|",
>             "2": "[EU]wAVE Bhop|Store|FastDL",  <-- Remove this comma
>     }
>
