### ISSUE TITLE
 An error occured while trying to send data to server 0.

### ISSUE THREAD

**Issue by DevulOLD** [Starfox64/FoxedBot#3]
Everything is set up, the bot reads chat logs from the server and such, but i can't announce or send messages to the server.

I can't send data from bot to server, but I can receive data from the server to the bot.

Any idea what's going on? Tell me if i need to give you more info

**Comment by Starfox64** [comment]
Are you sure that the configuration is right, if yes are you running on a dedicated server or just renting a Gmod Server?

**Comment by DevulOLD** [comment]
I'm running the bot and server on Ubuntu latest version. (dedicated server). The configuration should be right. I'm not sure what you mean by config being correct, but there is one line on the lua version that makes no sense to me. The difference between the BotPort and ServerPort. The ServerPort, what is that?

**Comment by Starfox64** [comment]
The ServerPort is the port that the Garry's Mod server will listen on AKA the port in the server config of the bot.
The BotPort is the port of the SteamBot.

If you kept the port as default in the bot's server config the ServerPort should be 25100 for ServerID 0.

**Comment by DevulOLD** [comment]
So it would be 27015, the same as the server I'm using?

**Comment by Starfox64** [comment]
FoxedBot is using a completely different port, it's not using source's. If you are setting up the first server you should set the ServerPort to 25100 and set the first server in the bot's config file to the same port.

_Second server would be 25101_

**Comment by DevulOLD** [comment]
Thanks. It seems to work now,  thought the port in the bot config meant the server's config. Was hard to tell.

**Comment by Starfox64** [comment]
Alright, I'll try to make this clearer in the install guide, make sure to give me some feedback on how the bot runs.
