### ISSUE TITLE
Second server with same IP can not be connected

### ISSUE THREAD

**Issue by CattoGamer** [Starfox64/FoxedBot#30]
I would like to connect a second server with the same IP address.
Although the ID of the second server is different, it still can not connect.

When I enter on the 2nd server this command `foxedbot_reload` I get this here
> [FoxedBot] Reloading connection...
> [FoxedBot] Disconnected!

At the same time at FoxedBot this
> [2017-08-15 11:18:08.199] [INFO] LOG - Socket undefined disconnected.

FoxedBot is running separately on another server with a different IP address.

Both Linux servers (Host and FoxedBot) running with Debian 8.6
FoxedBot is running with Node.js v6.11.2 LTS

**Comment by Starfox64** [comment]
Is this the architecture you are describing ?
![untitled diagram](https://user-images.githubusercontent.com/1530720/29316996-5d4437d8-81ca-11e7-951a-fd412afc6055.png)

Could you give me your config files (with passwords redacted).

**Comment by FarukGamer** [comment]
Yes, exactly as it is in the picture

**Setting.js**
```
module.exports = {
        /* The name of the SteamBot */
        botName: "The_Overwatcher",

        /* The Steam username and password of the SteamBot */
        accountName: "xxxxxxxxxx",
        password: "xxxxxxxxxxxxxxxxxxxx",

        /* Enter location for ShaSentryFile */
        sentryfile: "./config/shasentry.bin",


        /* The ServerKey of the SteamBot */
        serverKey: "xxxxxxxxxxxxxxxxxxxx",

        /* The port that the SteamBot will listen on */
        botPort: 25000,


        /* The level of logging (TRACE/DEBUG/INFO/WARN/ERROR/FATAL) */
        logLevel: "INFO",

        /* Log ALL chat message (Not recommended unless debugging) */
        logChat: false,

        /* Sends messages even if the target is offline */
        sendOffline: false,

        /* Which SteamID64 are superadmins */
        admins: [
                "76561198112042939", // Shadowsun
                "76561198086574406" // Darkiii
        ],

        /* Your Garry's Mod servers */
        servers: {
                "1": "Cinema",
                "2": "Guess Who"
        }
};

```

**GMOD # 1**
```
-- ServerID: A unique number to identify the server with the bot.
FoxedBot.ServerID = 1

-- BotIP: The IP address of the SteamBot.
FoxedBot.BotIP = "84.200.62.2xx"

-- BotPort: The port of the SteamBot.
FoxedBot.BotPort = 25000

-- ServerKey: A key / password used to secure interactions between the server and the bot.
FoxedBot.ServerKey = "xxxxxxxxxxxxxxxxxxxx"

-- FEATURES --
-- SendChat: Send the server's chat to the SteamBot.
FoxedBot.SendChat = true

-- AdminCaller: Enables or disables the Admin Caller functionality of FoxedBot.
FoxedBot.AdminCaller = false

-- AdminCallerCommand: The chat command used to call an admin.
FoxedBot.AdminCallerCommand = "!calladmin"

-- AdminCallerCooldown: The amount of time required before someone can send another admin call. (seconds)
FoxedBot.AdminCallerCooldown = 60

-- AdminCallerMin: The minimum amount of characters required to send an admin call.
FoxedBot.AdminCallerMin = 5

-- LogConnections: Send connects and disconnects to the SteamBot.
FoxedBot.LogConnections = true

-- LogDeaths: Send player deaths to the SteamBot.
FoxedBot.LogDeaths = true

-- BanAddon: The addon that should be used to ban players. (default/ulx/evolve/moderator)
FoxedBot.BanAddon = "ulx"

```

**GMOD # 2**
```
-- ServerID: A unique number to identify the server with the bot.
FoxedBot.ServerID = 2

-- BotIP: The IP address of the SteamBot.
FoxedBot.BotIP = "84.200.62.2xx"

-- BotPort: The port of the SteamBot.
FoxedBot.BotPort = 25000

-- ServerKey: A key / password used to secure interactions between the server and the bot.
FoxedBot.ServerKey = "xxxxxxxxxxxxxxxxxxxx"

-- FEATURES --
-- SendChat: Send the server's chat to the SteamBot.
FoxedBot.SendChat = true

-- AdminCaller: Enables or disables the Admin Caller functionality of FoxedBot.
FoxedBot.AdminCaller = true

-- AdminCallerCommand: The chat command used to call an admin.
FoxedBot.AdminCallerCommand = "!calladmin"

-- AdminCallerCooldown: The amount of time required before someone can send another admin call. (seconds)
FoxedBot.AdminCallerCooldown = 60

-- AdminCallerMin: The minimum amount of characters required to send an admin call.
FoxedBot.AdminCallerMin = 5

-- LogConnections: Send connects and disconnects to the SteamBot.
FoxedBot.LogConnections = true

-- LogDeaths: Send player deaths to the SteamBot.
FoxedBot.LogDeaths = true

-- BanAddon: The addon that should be used to ban players. (default/ulx/evolve/moderator)
FoxedBot.BanAddon = "ulx"

```

**Comment by FarukGamer** [comment]
I am not sure if this problem a Bromsock or FoxedBot issue. But it seems more likely that FoxedBot doesn't support simultaneously connections of the same IP.

**Comment by Starfox64** [comment]
I don't think it's coming from IPs, I don't use them to identify servers, only the ServerID matters.
Does changing the boot order of your GMOD servers change anything? Is it always the second server that connects that fails?

**Comment by FarukGamer** [comment]
I tried to change the boot order, but it did not work. I do not understand why only the first one works

**Comment by Starfox64** [comment]
At this point the next step would be to do a packet capture to see what's going wrong.

**Comment by FarukGamer** [comment]
Alright but I try other possibilities first.

**Comment by FarukGamer** [comment]
Well, I've tried shutting down the first server and just starting the second one.
It seems only to have problems with the authentication or connetion.

**Comment by FarukGamer** [comment]
I tried reinstalling the Server where FoxedBot is installed, its  Running with Ubuntu 16.04 now. The results are the same.

it seems like FoxedBot Is detecting the Second Gmod server, it's just not authenticating.

In addition I tired changing the ID's, Ports and Bromsock modules.
The current bromsock module is gmsv_bromsock_linux_debian.dll

**Comment by FarukGamer** [comment]
I still have that issue but it doesn't bother me much.
I made "lsof -PNL +M -i4" on the server to check the listen ports, the #1 Gameserver is established with to the listening TCP port 25000 on the Linux server.

I just seems that this listening port does not allow multiple in/outcoming sockets. Like for #2 Gamerserver

**Comment by Starfox64** [comment]
Definitely weird, I really don't know whats causing this, if you know people who use the FoxedBot, you might want to ask them if they are having trouble running multiple servers with it, I'd like to know whether or not it's an isolated incident.

**Comment by Dexelir** [comment]
--to server.cfg
sv_hibernate_think 1

it may work.
