### ISSUE TITLE
[Suggestion] Ability to send message to single person on Bot's friends list

### ISSUE THREAD

**Issue by DevulOLD** [Starfox64/FoxedBot#4]
Instead of !admin sending to all Bot's friends, one that focuses on one person in particular?

Or is this too much hassle for one little thing?

**Comment by DevulOLD** [comment]
I've just noticed there's the ability to make commands. But I have no idea how to use JS ^^

**Comment by Starfox64** [comment]
I'll probably add that in the next update.

**Comment by DevulOLD** [comment]
Nice! By the way, I've been running commands such as !kick Devul from the bot and my server crashed? I'll grab the error if and when it happens again.

Here's the error.

> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Aborted (core dumped)

**Comment by DevulOLD** [comment]
I created a pull request for my (probably horrible) iteration of this.

https://github.com/Starfox64/FoxedBot/pull/7

**Comment by Starfox64** [comment]
That error is probably an issue with bromsock, keep using these commands and tell me if it crashes again.

I'll look into you pull request, I'll need to change a few things.

**Comment by Starfox64** [comment]
Added
