### ISSUE TITLE
[Suggestion/Bug?] Call Admin sends to everyone on the Bot's friends list, not Admins.

### ISSUE THREAD

**Issue by DevulOLD** [Starfox64/FoxedBot#6]
It would be ideal if the bot sent messages to admins only not everyone. Tried fixing myself but JS is unknown to me, func.isAdmin(i) was unknown and it crashed.

**Comment by Starfox64** [comment]
FoxedBot admins shouldn't be considered admins you should see them as superadmin or bot managers. All friends should be considered admins.

**Comment by DevulOLD** [comment]
Oh, I see. That's another thing I didn't qute understand, thanks man.
