### ISSUE TITLE
Is it supposed to lag the server?

### ISSUE THREAD

**Issue by theantihero** [Starfox64/FoxedBot#8]
Whenever I run a rcon command or chat, it lags the server for like 3-5 seconds. Is that normal?

If it is normal, is there any way to fix this?

**Comment by Starfox64** [comment]
No it's not, does this happens with all rcon commands and does this happens with other FoxedBot commands?

**Comment by theantihero** [comment]
With normal commands such as like !who and !listen works perfectly fine. It seems to do this when it's trying to execute !rcon commands or the !chat command. As well as the !kick, !kickid, !ban, !banid, !announce. Like almost anything that's communicating between server and bot seems to lag up the server. Creates a loss of connection between normal users and server for like 2-4 seconds for me. Server is run off Linux VPS. However, the !listen command seems to work fine with no lag at all.

**Comment by theantihero** [comment]
Especially for DarkRP like some commands will come back with an error "An error occured while trying to send data to server 1." Sometimes works and sometimes doesn't. When it gives that error, the server crashes and restarts. For TTT, while it doesn't crash, sometimes does not connect between bot and server. The connection between it is inconsistent.

**Comment by theantihero** [comment]
I just tested the server and bot on the same server. Problem still occurs.

**Comment by Starfox64** [comment]
I'll tell this to the creator of bromsock so I can fix this issue.

**Comment by Bromvlieg** [comment]
Hello there!

I've spoken to Starfox, and the current code does not use threaded mode, but blocking mode. That's why it blocks for a few seconds sending data.

**Comment by theantihero** [comment]
Is it possible to fix this in the future update you can release? It's kind of annoying when everyone experiences like a 4 second disconnect whenever you are trying to send a chat to the server or anything else.

**Comment by Starfox64** [comment]
Could install the latest update (Bot & Server) and tell me if you still have any issues.

**Comment by theantihero** [comment]
Thanks!! :D Updating it fixed the issue with the connection lag. running rcon commands are instant or chat commands. Thanks for the update Starfox! xD
